[tool.poetry]
name = "genshin-auto-daily-check-in-docker"
version = "1.4.0"
description = "원신 호요랩 자동 출석체크 도커 이미지. 여러 계정을 한번에 등록할 수 있습니다."
authors = ["Bingsu <ks2515@naver.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
genshin = "^1.6.0"
rich = "*"
schedule = "*"

[tool.poetry.group.dev.dependencies]
black = "*"
isort = "*"
ruff = "*"
python-dotenv = "*"
pre-commit = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.ruff]
select = [
    "A",
    "B",
    "C4",
    "C90",
    "E",
    "EM",
    "F",
    "FA",
    "FURB",
    "I001",
    "ISC",
    "N",
    "PERF",
    "PIE",
    "PT",
    "PTH",
    "RET",
    "RUF",
    "SIM",
    "T20",
    "UP",
    "W",
]
ignore = ["B008", "B905", "E501"]
unfixable = ["F401"]
