[tool.poetry]
name = "genshin-auto-daily-check-in-docker"
version = "1.3.3"
description = "원신 호요랩 자동 출석체크 도커 이미지. 여러 계정을 한번에 등록할 수 있습니다."
authors = ["Bingsu <ks2515@naver.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
genshin = "^1.6.0"
rich = "*"
schedule = "*"

[tool.poetry.group.dev.dependencies]
black = ">=22.3.0"
isort = "*"
ruff = "*"
python-dotenv = "*"
mypy = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.ruff]
select = ["A", "B", "C4", "E", "F", "I001", "ISC", "N", "PIE", "PT", "RET", "SIM", "UP", "W"]
ignore = ["B008", "B905", "E501"]
unfixable = ["F401"]
