# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task --list
    silent: true

  update:
    cmds:
      - uv sync --all-extras --all-groups --upgrade
      - pre-commit autoupdate --jobs 5
    desc: Update all dependencies

  export:
    cmds:
      - uv export -o requirements.txt --no-group dev
    desc: Export lock file to requirements.txt

  docker:
    cmds:
      - docker buildx bake {{ .CLI_ARGS }}
    desc: Build docker image
